// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSe0Xza3KQjad9hocV77qvssWgRxaVSA',
    appId: '1:1059294323629:web:915c9290239739c95a7724',
    messagingSenderId: '1059294323629',
    projectId: 'food19122022',
    authDomain: 'food19122022.firebaseapp.com',
    storageBucket: 'food19122022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvok4tGeAN-dYrqdWNYTGcjz6EXif840w',
    appId: '1:1059294323629:android:c39c21b7012007315a7724',
    messagingSenderId: '1059294323629',
    projectId: 'food19122022',
    storageBucket: 'food19122022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7SP2SfqaYdzNxa8tgj2nI2dk8xWrjc-o',
    appId: '1:1059294323629:ios:f18c4d829a6ab5625a7724',
    messagingSenderId: '1059294323629',
    projectId: 'food19122022',
    storageBucket: 'food19122022.appspot.com',
    iosClientId: '1059294323629-6o0rqiloa0hioto2epkk585v0iuo3e1b.apps.googleusercontent.com',
    iosBundleId: 'com.rafalkupczyk.food',
  );
}
